version: "3.8"

services:
  removearr:
    image: nandi95/removearr:main
    container_name: removearr
    environment:
      - TAUTULLI_API_KEY=${TAUTULLI_API_KEY}
      - TAUTULLI_API_URL=${TAUTULLI_API_URL}
      - TAUTULLI_NOTIFIER_ID=${TAUTULLI_NOTIFIER_ID}
      - DELETE_AFTER_DAYS=${DELETE_AFTER_DAYS}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_API_URL=${RADARR_API_URL}
    restart: unless-stopped
